const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{fundo: 0},
	{Sólido: 0},
	{bloco: 0},
	{Fixar: 0},
	{animação: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{ação: 0},
	{rato: 0},
	{borda: 0},
	{lava: 0},
	{fogo: 0},
	{Senóide: 0},
	{moeda: 0},
	{armadilha: 0},
	{Órbita: 0},
	{bolaDeFogo: 0},
	{porta: 0},
	{Âncora: 0},
	{txtscore: 0},
	{txtmoeda: 0},
	{Projétil: 0},
	{magia: 0},
	{inimigo: 0},
	{Sprite: 0},
	{vidas: 0},
	{bruxa: 0},
	{barreira: 0},
	{Sprite3: 0},
	{Áudio: 0},
	{Sprite5: 0},
	{Botão: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{score: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	fundo: class extends self.ITiledBackgroundInstance {},
	bloco: class extends self.ITiledBackgroundInstance {},
	animação: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	rato: class extends self.ISpriteInstance {},
	borda: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	fogo: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	armadilha: class extends self.ISpriteInstance {},
	bolaDeFogo: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	txtscore: class extends self.ITextInstance {},
	txtmoeda: class extends self.ITextInstance {},
	magia: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bruxa: class extends self.ISpriteInstance {},
	barreira: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}